import React from 'react';
import { useLearningStreak } from '../../hooks/useLearningStreak';

const level = count => count === 0 ? 0 : count === 1 ? 1 : count === 2 ? 2 : count <= 4 ? 3 : 4;
export function LearningStreak() {
  const { weeks, months, totalActivities, activeDays, maxStreak } = useLearningStreak();
  const monthStarts = new Set(months.map(month => month.firstWeekIndex));
  return <section className="streak-panel dashboard-panel"><div className="learning-activity-heading"><div><h2><strong>{totalActivities}</strong> learning activities in the past one year <span className="activity-info" title="Shows your daily learning activity over the past year." aria-label="Shows your daily learning activity over the past year.">i</span></h2><p>Your consistency is your superpower.</p></div><div className="learning-activity-stats"><span>Total active days: <b>{activeDays}</b></span><span>Max streak: <b>{maxStreak}</b></span></div></div><div className="heatmap-wrap"><div className="learning-calendar-scroll"><div className="heatmap-months"><span className="weekday-spacer" />{months.map((month, index) => <span className="month-segment" style={{ '--month-weeks': month.weekCount }} key={`${month.label}-${index}`}>{month.label}</span>)}</div><div className="learning-calendar-body"><div className="learning-weekdays"><span>Mon</span><span>Wed</span><span>Fri</span></div><div className="heatmap-grid" aria-label="Learning activity calendar">{weeks.map((week, index) => <div className={monthStarts.has(index) ? 'heatmap-week month-start' : 'heatmap-week'} key={index}>{week.map(cell => <span tabIndex="0" key={cell.id} className={`activity-cell level-${level(cell.activities)} ${cell.inRange ? '' : 'outside'}`} title={`${cell.date.toLocaleDateString()} — ${cell.activities ? `${cell.activities} learning ${cell.activities === 1 ? 'activity' : 'activities'}` : 'No learning activity'}`} aria-label={`${cell.date.toLocaleDateString()} — ${cell.activities ? `${cell.activities} learning activities` : 'No learning activity'}`} />)}</div>)}</div></div></div></div><div className="heatmap-legend"><span>Less</span><i className="level-0" /><i className="level-1" /><i className="level-2" /><i className="level-3" /><i className="level-4" /><span>More</span></div></section>;
}
