export const APTITUDE_CATEGORIES = [
 { id:'quantitative', name:'Quantitative Aptitude', icon:'ΓùÄ', description:'Master arithmetic and mathematical concepts commonly used in placement assessments.', topics:16, questions:240, progress:42, premium:true, difficulty:'Easy ΓåÆ Hard' },
 { id:'logical', name:'Logical Reasoning', icon:'Γîü', description:'Strengthen structured thinking with patterns, arrangements and deductions.', topics:14, questions:190, progress:28, premium:true, difficulty:'Easy ΓåÆ Hard' },
 { id:'verbal', name:'Verbal Ability', icon:'Aa', description:'Improve comprehension, grammar, vocabulary and communication accuracy.', topics:10, questions:150, progress:51, premium:true, difficulty:'Easy ΓåÆ Medium' },
 { id:'data-interpretation', name:'Data Interpretation', icon:'ΓûÑ', description:'Read tables, charts and caselets with speed and confidence.', topics:6, questions:90, progress:12, premium:true, difficulty:'Medium ΓåÆ Hard' },
];
export const APTITUDE_TOPICS = { quantitative:[['number-system','Number System','Understand numbers, divisibility and remainders.','Easy',20,true,70],['percentages','Percentages','Learn percentage increase, decrease and comparisons.','Easy ΓåÆ Medium',25,true,32],['profit-loss','Profit & Loss','Solve selling price, cost price and discount problems.','Medium',30,false,0],['time-work','Time & Work','Solve work-rate and efficiency based problems.','Medium',30,false,0]], logical:[['number-series','Number Series','Identify patterns and missing terms.','Easy',18,true,25],['coding-decoding','Coding-Decoding','Decode rules and transform information.','Easy ΓåÆ Medium',20,true,0],['seating-arrangement','Seating Arrangement','Build a clear method for arrangement problems.','Hard',25,false,0]], verbal:[['reading-comprehension','Reading Comprehension','Read with purpose and identify the authorΓÇÖs intent.','Medium',20,true,40],['vocabulary','Vocabulary','Build useful placement vocabulary in context.','Easy',25,true,60],['sentence-correction','Sentence Correction','Spot grammar and usage errors.','Medium',20,false,0]], 'data-interpretation':[['tables','Tables','Compare values and calculate change from tabular data.','Easy ΓåÆ Medium',15,true,20],['bar-charts','Bar Charts','Extract accurate insights from bar charts.','Medium',15,false,0]]};
export const APTITUDE_QUESTIONS = [{id:'percent-001',topicId:'percentages',question:'A value increases from 200 to 240. What is the percentage increase?',options:['10%','15%','20%','25%'],correctAnswer:2,explanation:'The increase is 40. 40 ├╖ 200 ├ù 100 = 20%.',free:true,difficulty:'Easy'},{id:'percent-002',topicId:'percentages',question:'What is 25% of 160?',options:['20','30','40','50'],correctAnswer:2,explanation:'25% is one quarter. 160 ├╖ 4 = 40.',free:true,difficulty:'Easy'},{id:'percent-003',topicId:'percentages',question:'A price falls from 500 to 450. What is the percentage decrease?',options:['5%','10%','15%','20%'],correctAnswer:1,explanation:'The decrease is 50. 50 ├╖ 500 ├ù 100 = 10%.',free:true,difficulty:'Easy'}];
export const APTITUDE_PROGRESS = { overall:34, attempted:120, accuracy:78, categories:[['Quantitative',42],['Logical Reasoning',28],['Verbal',51],['Data Interpretation',12]] };
