import React from 'react';
import { Arrow } from '../../components/common/Logo';
import { LANDING_FEATURES } from '../../constants/landing';
import { useCompanies } from '../../hooks/useCompanies';
import { useAuth } from '../../context/AuthContext';
import heroVisual from '../../assets/placepro-dsa-student-hero.png';

function LandingHero({ isAuthenticated }) {
  const startLearning = () => { window.location.href = isAuthenticated ? '/learning' : '/login?from=%2Flearning'; };
  return <section className="landing-hero"><div className="landing-hero-inner"><div className="landing-hero-content"><div className="landing-hero-eyebrow"><span className="pulse" /> LEARN · PRACTICE · PREPARE · GET PLACED</div><h1>Your placement <em>journey starts here.</em></h1><p className="landing-hero-description">Build the skills you need for placements with structured learning, focused practice, mock tests, and company-wise preparation — all in one place.</p><div className="landing-hero-actions"><button className="button" onClick={startLearning}>Start learning <Arrow /></button><button className="text-button" onClick={() => document.querySelector('#companies')?.scrollIntoView({ behavior: 'smooth' })}>Explore companies <Arrow /></button></div><div className="landing-hero-social-proof"><div className="avatar-stack"><i>R</i><i>A</i><i>M</i><i>+</i></div><span>Join 10,000+ students building their future</span></div></div><div className="landing-hero-visual"><img src={heroVisual} alt="Engineering student learning DSA and solving coding problems at a computer" /></div></div></section>;
}

function FeatureGrid() { return <div className="feature-grid">{LANDING_FEATURES.map(feature => <article className="feature-card" key={feature.title}><div className={`feature-icon ${feature.tone}`}>{feature.icon}</div><div className="feature-tag">{feature.tag}</div><h3>{feature.title}</h3><p>{feature.text}</p><button className="card-link">Explore <Arrow /></button></article>)}</div>; }
function Pricing() { return <section className="section pricing-section"><div className="section-heading centered"><span className="section-kicker">START WHERE YOU ARE</span><h2>Build your foundation.<br /><em>Go further when you're ready.</em></h2><p>Free learning that is genuinely useful. Premium preparation when you want to go deeper.</p></div><div className="plans"><article className="plan"><div className="plan-head"><div><span className="plan-label">THE FOUNDATION</span><h3>Free</h3></div><strong>₹0</strong></div><p>Everything you need to start building your placement skills.</p><ul><li>Academic resources &amp; semester notes</li><li>DSA fundamentals and basic practice</li><li>Limited aptitude content</li><li>Basic tests and progress tracking</li></ul><button className="outline-button">Start for free <Arrow /></button></article><article className="plan premium"><div className="premium-glow" /><div className="plan-head"><div><span className="plan-label">THE COMPLETE JOURNEY <b>POPULAR</b></span><h3>Premium</h3></div><strong>₹199<span>/mo</span></strong></div><p>Everything you need to prepare with confidence and stand out.</p><ul><li>Complete aptitude and advanced practice</li><li>Company-wise preparation and mock tests</li><li>Detailed analytics and smart roadmaps</li><li>Interview preparation resources</li></ul><button className="button full">Explore premium <Arrow /></button></article></div></section>; }
function CompanySection() { const { data, loading, error } = useCompanies(); return <section className="companies-section" id="companies"><div className="page-width company-content"><div><span className="section-kicker">PREPARE WITH A PURPOSE</span><h2>Have a company<br /><em>in mind?</em></h2><p>Turn your target into a plan. Explore preparation paths designed around the patterns and skills that matter.</p><button className="text-button">View all companies <Arrow /></button></div><div className="company-grid">{loading && <p className="company-status">Loading companies…</p>}{error && <p className="company-status">Companies are temporarily unavailable.</p>}{!loading && !error && data.map((company, index) => <div className="company-pill" key={company.name}><span className={`company-logo logo-${index}`}>{company.name[0]}</span><div><strong>{company.name}</strong><small>{company.category}</small></div><Arrow /></div>)}</div></div></section>; }

export function LandingPage() { const { isAuthenticated } = useAuth(); return <><LandingHero isAuthenticated={isAuthenticated} /><section className="journey-strip"><div className="page-width journey"><span>Everything you need to prepare with confidence</span><div className="journey-items"><b><i>01</i> Learn</b><span>→</span><b><i>02</i> Practice</b><span>→</span><b><i>03</i> Test</b><span>→</span><b className="highlight"><i>04</i> Get placed</b></div></div></section><Pricing /><CompanySection /></>; }
