import React from 'react';
import { Arrow } from '../../components/common/Logo';
import { LANDING_FEATURES } from '../../constants/landing';
import { useCompanies } from '../../hooks/useCompanies';
import { useAuth } from '../../context/AuthContext';

function DashboardPreview() {
  return <div className="hero-visual"><div className="visual-glow" /><div className="dashboard-card main-preview"><div className="preview-top"><span className="window-dots">● ● ●</span><span className="preview-label">MY PROGRESS</span><span className="more">•••</span></div><div className="welcome-line"><div><small>Good morning, Arjun</small><h3>Keep going — you're doing great.</h3></div><span className="sun">☼</span></div><div className="metric-grid"><div><span className="metric-icon blue">⌘</span><small>Questions solved</small><strong>248</strong><b>+18 this week</b></div><div><span className="metric-icon purple">◔</span><small>Learning progress</small><strong>64%</strong><b>On track</b></div></div><div className="chart"><div className="chart-head"><span>Learning activity</span><small>Last 7 days⌄</small></div><div className="bars">{[38, 58, 45, 74, 56, 92, 64].map((height, i) => <i key={i} className={i === 5 ? 'today' : ''} style={{ height: `${height}%` }} />)}</div><div className="days"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></div></div><div className="floating-card streak-card"><span className="streak-icon">✦</span><div><small>Current streak</small><strong>12 days <b>↗</b></strong></div></div><div className="floating-card target-card"><div className="target-ring"><span>78%</span></div><div><small>Placement goal</small><strong>On your way</strong></div></div></div>;
}

function FeatureGrid() { return <div className="feature-grid">{LANDING_FEATURES.map(feature => <article className="feature-card" key={feature.title}><div className={`feature-icon ${feature.tone}`}>{feature.icon}</div><div className="feature-tag">{feature.tag}</div><h3>{feature.title}</h3><p>{feature.text}</p><button className="card-link">Explore <Arrow /></button></article>)}</div>; }

function Pricing() { return <section className="section pricing-section"><div className="section-heading centered"><span className="section-kicker">START WHERE YOU ARE</span><h2>Build your foundation.<br /><em>Go further when you're ready.</em></h2><p>Free learning that is genuinely useful. Premium preparation when you want to go deeper.</p></div><div className="plans"><article className="plan"><div className="plan-head"><div><span className="plan-label">THE FOUNDATION</span><h3>Free</h3></div><strong>₹0</strong></div><p>Everything you need to start building your placement skills.</p><ul><li>Academic resources & semester notes</li><li>DSA fundamentals and basic practice</li><li>Limited aptitude content</li><li>Basic tests and progress tracking</li></ul><button className="outline-button">Start for free <Arrow /></button></article><article className="plan premium"><div className="premium-glow" /><div className="plan-head"><div><span className="plan-label">THE COMPLETE JOURNEY <b>POPULAR</b></span><h3>Premium</h3></div><strong>₹199<span>/mo</span></strong></div><p>Everything you need to prepare with confidence and stand out.</p><ul><li>Complete aptitude and advanced practice</li><li>Company-wise preparation and mock tests</li><li>Detailed analytics and smart roadmaps</li><li>Interview preparation resources</li></ul><button className="button full">Explore premium <Arrow /></button></article></div></section>; }

function CompanySection() { const { data, loading, error } = useCompanies(); return <section className="companies-section" id="companies"><div className="page-width company-content"><div><span className="section-kicker">PREPARE WITH A PURPOSE</span><h2>Have a company<br /><em>in mind?</em></h2><p>Turn your target into a plan. Explore preparation paths designed around the patterns and skills that matter.</p><button className="text-button">View all companies <Arrow /></button></div><div className="company-grid">{loading && <p className="company-status">Loading companies…</p>}{error && <p className="company-status">Companies are temporarily unavailable.</p>}{!loading && !error && data.map((company, index) => <div className="company-pill" key={company.name}><span className={`company-logo logo-${index}`}>{company.name[0]}</span><div><strong>{company.name}</strong><small>{company.category}</small></div><Arrow /></div>)}</div></div></section>; }

export function LandingPage() {
  const { isAuthenticated } = useAuth(); const startLearning = () => { window.location.href = isAuthenticated ? '/learning' : '/login?from=%2Flearning'; };
  return <><section className="hero page-width"><div className="hero-copy"><div className="eyebrow"><span className="pulse" /> LEARN · PRACTICE · PREPARE · GET PLACED</div><h1>Your placement<br /><em>journey starts here.</em></h1><p className="hero-description">Build the skills you need for placements with structured learning, focused practice, mock tests, and company-wise preparation — all in one place.</p><div className="hero-actions"><button className="button" onClick={startLearning}>Start learning <Arrow /></button><button className="text-button" onClick={() => document.querySelector('#companies')?.scrollIntoView({ behavior: 'smooth' })}>Explore companies <Arrow /></button></div><div className="trust-row"><div className="avatar-stack"><i>R</i><i>A</i><i>M</i><i>+</i></div><span>Join 10,000+ students building their future</span></div></div><DashboardPreview /></section><section className="journey-strip"><div className="page-width journey"><span>Everything you need to prepare with confidence</span><div className="journey-items"><b><i>01</i> Learn</b><span>→</span><b><i>02</i> Practice</b><span>→</span><b><i>03</i> Test</b><span>→</span><b className="highlight"><i>04</i> Get placed</b></div></div></section><Pricing /><CompanySection /></>;
}
